cat \
	ecssentric.config.css \
	ecssentric.reset.css \
	ecssentric.layout.css \
	ecssentric.typography.css \
	ecssentric.buttons.css \
	ecssentric.forms.css \
	ecssentric.grid.css \
	ecssentric.messages.css \
	ecssentric.tables.css \
	ecssentric.scrollbars.css \
	> ecssentric.css
